# Site settings
title: Dafonse
email:
description: >
  Portfólio profissional de engenharia, inteligência artificial, visão computacional,
  automação, robótica e desenvolvimento de produtos digitais.
lang: pt-BR

baseurl: "/site"
url: https://dafonse.github.io/site
git_address: https://github.com/dafonse
git_edit_address: https://github.com/dafonse/site/blob/gh-pages

# theme options from https://bootswatch.com/3/
# comment out this to use default Bootstrap
bootwatch: readable

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - .idea/
  - .gitignore
  - README.md
timezone: America/Sao_Paulo

defaults:
- scope:
    path: _posts
    type: posts
  values:
    layout: post
    sectionid: blog

- scope:
    path: _docs
    type: docs
  values:
    layout: docs
    sectionid: docs
    seo:
      type: "WebPage"

collections:
  docs:
    permalink: /:collection/:path/
    output: true
  posts:
    permalink: /blog/:year/:month/:day/:title/
    output: true
